export const FETCH_PEOPLE_REQUEST = 'FETCH_REQUEST';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const SAVE_PEOPLE_REQUEST = 'SAVE_REQUEST';
export const SAVE_PEOPLE_FAILURE = 'SAVE_PEOPLE_FAILURE';
export const SAVE_PEOPLE_SUCCESS = 'SAVE_PEOPLE_SUCCESS';
